openapi: 3.0.3
info:
  title: Share Docs Pub - OpenAPI 3.0
  description: |
    -  文書管理APIエンドポイント
        -  文書と文書属性の登録
        -  文書属性による文書の検索
            以下の検索条件を組み合わせて検索するものとする
            結果に文書ファイルは含まず文書属性を返す
              -  指定したキーと値の一致
              -  指定したキーの値が指定した値の範囲に含まれるか
        -  文書ファイルの更新
        -  文書属性の更新
        -  文書ファイルの取得
        -  文書の削除
    -  文書ファイルは1ファイルあたり最大1GBまでのPDF/Word/Excel/Image/Videoとする
    -  Webアプリケーションが使用できるメモリ量は100MBまでとする
    -  文書の属性は任意のキー(英数字)と値で設定することができる
    -  文書にはそれぞれ一意なキーやURLが割り振られ、外部システムで利用可能であること
    -  当APIは外部へ公開し任意の利用者がいる想定とする

  # termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.00
# externalDocs:
#   description: Find out more about Swagger
#   url: http://swagger.io
servers:
  - url: http://localhost/api/v1/
tags:
  - name: 文書
    description: 文書の新規登録、検索、削除
  - name: 文書の属性
    description: 文書属性の更新
  - name: 文書ファイル
    description: 文書ファイルの取得、ファイルの更新
paths:
  /documents:
    post:
      tags:
        - 文書
      summary: 文書の登録
      description: |
        |対応するファイルの種類|
        |-|
        |PDF/Word/Excel/Image/Video|

        |リクエスト時のHTTPヘッダー|指定値|
        |-|-|
        |Content-Type|multipart/form-data|

        |入力チェック|status|message|
        |-|-|-|
        |・HTML要素のname属性の値を"file"で<br>バイナリーファイルをリクエストされていること|400|入力値が不正です|
        |・name属性の値が"file"は、1つのみとする|↑|↑|
        |・入力されたファイルは、対応したmime_typeであること|↑|↑|
        |・文書の属性を入力する場合は、<br>"attribute[title]: API基本設計仕様書"のように<br>[]内に文書の属性のkey値として指定したいname属性を入力し、<br>フォームの入力値も入力していること|↑|↑|
        |・文書の属性のname属性の値([]の中)は英数字のみ(10字まで)入力可<br>そのフォームに入力された値は任意(20字まで)|↑|↑|

        |登録後|
        |-|
        |・登録後のレスポンスは、登録されたファイルの情報が表示される(レスポンス例を参照)|

        |例外処理|
        |-|
        |・例外種類に応じて、Response例の通りに返すこと|
        |・また、例外が発生した場合はログを残すこと|
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                attribute[]:
                  description: |
                    文書の属性の入力例：

                    `"attribute[title]": "API基本設計仕様書"`<br>
                    ※日付を入力する場合は、`2023-03-03`の形式で入力すること
                  type: string
                  additionalProperties: true
              required: ["file"]
              example:
                key: api
      responses:
        "200":
          $ref: "#/components/responses/register"
        "400":
          $ref: "#/components/responses/400"
        "404":
          $ref: "#/components/responses/404"
        "405":
          $ref: "#/components/responses/405"
        "500":
          $ref: "#/components/responses/500"
    get:
      tags:
        - 文書
      summary: 文書の検索
      description: |
        |存在チェック|status|message|
        |-|-|-|
        |・文書の属性のkeyが一致する|400|入力値が不正です|

        |入力チェック|status|message|
        |-|-|-|
        |・keyはname属性を、[]の中で比較する演算子を指定し、<br>valueで検索したい値を入力する<br>※比較演算子はエンコードされていること|400|入力値が不正です|
        |・文書の属性のkeyが一致した場合、<br>そのkeyのvalueと一致するか(部分一致)|↑|↑|
        ※日付を入力する場合は、`2023-03-03`の形式で入力すること

        |name属性に指定する比較演算子|検索内容|
        |-|-|
        |=|部分一致するものを対象|
        |>|検索値より大きいものを対象|
        |<|検索値より小さいもの(未満)を対象|
        |>=|左辺が右辺より大きいか等しい（以上）|
        |<=|左辺が右辺より小さいか等しい（以下）|
        *比較演算子は、エンコードして入力されていること

        |検索して合致した場合|
        |-|
        |・文書属性は、登録された全ての属性を出力する|

        |例外処理|
        |-|
        |・例外種類に応じて、Response例の通りに返すこと|
        |・また、例外が発生した場合はログを残すこと|
      parameters:
        - in: query
          name: key[*]
          schema:
            type: string
          required: true
          description: |
            タイトルが音楽のものを検索する場合<br>
            ※[]の中の比較演算子はエンコードし入力されていること
          example: ?title[=]=音楽
      responses:
        "200":
          $ref: "#/components/responses/documents_details"
        "400":
          $ref: "#/components/responses/400"
        "404":
          $ref: "#/components/responses/404"
        "405":
          $ref: "#/components/responses/405"
        "500":
          $ref: "#/components/responses/500"
  /documents/{document_number}:
    delete:
      tags:
        - 文書
      summary: 文書の削除
      description: |
        |存在チェック|status|message|
        |-|-|-|
        |・文書番号が一致していること(完全一致)|400|入力値が不正です|

        |例外処理|
        |-|
        |・例外種類に応じて、Response例の通りに返すこと|
        |・また、例外が発生した場合はログを残すこと|
      parameters:
        - in: path
          name: document_number
          schema:
            type: integer
          required: true
          description: 文書番号
      responses:
        "204":
          description: 成功
        "400":
          $ref: "#/components/responses/400"
        "404":
          $ref: "#/components/responses/404"
        "405":
          $ref: "#/components/responses/405"
        "500":
          $ref: "#/components/responses/500"
  /documents/{document_number}/attributes/{key}:
    patch:
      tags:
        - 文書の属性
      summary: 文書の属性の更新
      description: |
        |存在チェック|status|message|
        |-|-|-|
        |・文書番号が一致していること(完全一致)|400|入力値が不正です|
        |・文書の属性のkeyが一致していること(完全一致)|↑|↑|

        |登録時|
        |-|
        |・文書番号が一致したとき、入力された文書の属性のkeyが存在していればその値を更新する<br>それ以外は新規登録|
        |・日付を入力する場合は、`2023-03-03`の形式で入力すること|

        |登録後|
        |-|
        |・文書の属性は登録されている分を出力すること|

        |例外処理|
        |-|
        |・例外種類に応じて、Response例の通りに返すこと|
        |・また、例外が発生した場合はログを残すこと|
      parameters:
        - in: path
          name: document_number
          schema:
            type: integer
          required: true
          description: 文書番号
        - in: path
          name: key
          schema:
            type: string
          required: true
          description: 文書の属性のkey
      requestBody:
        description: 更新する属性
        $ref: "#/components/requestBodies/attributes"
      responses:
        "200":
          $ref: "#/components/responses/documents_detail"
        "400":
          $ref: "#/components/responses/400"
        "404":
          $ref: "#/components/responses/404"
        "405":
          $ref: "#/components/responses/405"
        "500":
          $ref: "#/components/responses/500"
    delete:
      tags:
        - 文書の属性
      summary: 文書の属性の削除
      description: |
        |存在チェック|status|message|
        |-|-|-|
        |・文書番号が一致していること(完全一致)|400|入力値が不正です|
        |・文書の属性のkeyが一致していること(完全一致)|↑|↑|

        |例外処理|
        |-|
        |・例外種類に応じて、Response例の通りに返すこと|
        |・また、例外が発生した場合はログを残すこと|
      parameters:
        - in: path
          name: document_number
          schema:
            type: integer
          required: true
          description: 文書番号
        - in: path
          name: key
          schema:
            type: string
          required: true
          description: 文書の属性のkey
      responses:
        "204":
          description: 成功
        "400":
          $ref: "#/components/responses/400"
        "404":
          $ref: "#/components/responses/404"
        "405":
          $ref: "#/components/responses/405"
        "500":
          $ref: "#/components/responses/500"
  /documents/{document_number}/file:
    get:
      tags:
        - 文書ファイル
      summary: 文書のダウンロード
      description: |
        |存在チェック|status|message|
        |-|-|-|
        |・文書番号が一致していること(完全一致)|400|入力値が不正です|

        |例外処理|
        |-|
        |・例外種類に応じて、Response例の通りに返すこと|
        |・また、例外が発生した場合はログを残すこと|
      parameters:
        - in: path
          name: document_number
          schema:
            type: integer
          required: true
          description: 文書番号
      responses:
        "200":
          $ref: "#/components/responses/download"
        "400":
          $ref: "#/components/responses/400"
        "404":
          $ref: "#/components/responses/404"
        "405":
          $ref: "#/components/responses/405"
        "500":
          $ref: "#/components/responses/500"
    patch:
      tags:
        - 文書ファイル
      summary: 文書の更新
      description: |
        |リクエスト時のHTTPヘッダー|指定値|
        |-|-|
        |Content-Type|multipart/form-data|

        |入力チェック|status|message|
        |-|-|-|
        |・HTML要素のname属性の値を"file"で<br>バイナリーファイルをリクエストされていること|400|入力値が不正です|
        |・name属性の値が"file"は、1つのみとする|↑|↑|
        |・文書番号が一致していること(完全一致)|↑|↑|
        |・登録しているファイルの拡張子と一致していること|↑|↑|

        |登録後|
        |-|
        |・登録後のレスポンスは、登録されたファイルの情報が表示される(レスポンス例を参照)|

        |例外処理|
        |-|
        |・例外種類に応じて、Response例の通りに返すこと|
        |・また、例外が発生した場合はログを残すこと|
      parameters:
        - in: path
          name: document_number
          schema:
            type: integer
          required: true
          description: 文書番号
      requestBody:
        description: 更新するファイル
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
              required: ["file"]
      responses:
        "200":
          $ref: "#/components/responses/register"
        "400":
          $ref: "#/components/responses/400"
        "404":
          $ref: "#/components/responses/404"
        "405":
          $ref: "#/components/responses/405"
        "500":
          $ref: "#/components/responses/500"
components:
  schemas:
    documents:
      properties:
        id:
          type: integer
          description: 文書id
        document_number:
          type: string
          description: 文書番号
        document_name:
          type: string
          description: 文書名
        document_mime_type:
          type: string
          description: 文書mimeタイプ
        document_extension:
          type: string
          description: 文書の拡張子
        created_at:
          type: string
          format: date-time
          description: 作成日
        updated_at:
          type: string
          format: date-time
          description: 更新日時
    attributes:
      properties:
        id:
          type: integer
        document_id:
          type: integer
        key:
          type: string
        value:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
  requestBodies:
    attributes:
      description: 文書の属性
      content:
        application/json:
          schema:
            type: object
            properties:
              value:
                type: string
                example: api
  responses:
    register:
      description: |
        ファイル登録時のレスポンス<br>
        *以下の属性は、更新不可(登録時の固定値)<br>
        *文書ファイルの更新時のみ更新される
          - document_number
          - document_name
          - document_mime_type
      content:
        application/json:
          schema:
            type: object
            properties:
              document_number:
                type: string
                example: dku7sjdjosUsdj89
              document_name:
                type: string
                example: specification_api
              document_mime_type:
                type: string
                example: application/pdf
              title:
                type: string
                example: API設計仕様書
              note:
                type: string
                example: ドキュメント管理のAPI設計書
    serach_item:
      description: 検索時の返却
      content:
        application/json:
          schema:
            type: object
            properties:
              document_name:
                type: string
                example: specification_api.pdf
              document_key:
                type: integer
                example: 1
              document_number:
                type: string
              optionals:
                type: object
              title:
                type: string
                example: none | api
              optional_value:
                type: string
                example: none | developer
    documents_detail:
      description: 文書の属性
      content:
        application/json:
          schema:
            type: object
            properties:
              document_number:
                type: string
                example: dku7sjdjosUsdj89
              document_name:
                type: string
                example: specification_api.pdf
              document_mime_type:
                type: string
                example: pdf
              title:
                type: string
                example: 公開作業手順書
              note:
                type: string
                example: Web公開手順
              created:
                type: string
                example: 2022.03.04
              updated:
                type: string
                example: 2023.01.12
    documents_details:
      description: |
        文書の検索結果一覧<br>
        検索で一致した文書の文書の属性を全て出力
      content:
        application/json:
          schema:
            oneOf:
              - type: object
                properties: {}
              - type: object
                properties:
                  items:
                   type: object
                   properties:
                    document_number:
                      type: string
                      example: dku7sjdjosUsdj89
                    document_name:
                      type: string
                      example: specification_api.pdf
                    document_mime_type:
                      type: string
                      example: pdf
                    title:
                      type: string
                      example: 公開作業手順書
                    note:
                      type: string
                      example: Web公開手順
                    created:
                      type: string
                      example: 2022-03-04
                    updated:
                      type: string
                      example: 2023-01-12
          example:
              [
                 {
                  document_number: dku7sjdjosUsdj89,
                  document_name: specification_api.pdf,
                  document_mime_type: application/pdf,
                  title: 公開作業手順書,
                  note: Web公開手順,
                  created: 2022-03-04,
                  updated: 2023-01-12
                },
                {
                  document_number: ss1soia9sasdoda,
                  document_name: API仕様書.pdf,
                  document_mime_type: application/pdf,
                  title: 公開作業手順書,
                  note: APIを公開するまで,
                  created: 2022-03-04,
                  updated: 2023-01-12
                },
              ]
    download:
      description: |
        ファイルダウンロード<br>
        *ファイルに応じたmime_typeを返す
      content:
        "application/pdf": {}
        ? "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
        : {}
        application/msword: {}
        application/vnd.openxmlformats-officedocument.spreadsheetml.sheet: {}
        application/vnd.ms-excel: {}
        image/png: {}
        image/jpeg: {}
        image/bmp: {}
        image/x-ms-bmp: {}
        image/svg+xml: {}
        audio/mpeg: {}
        video/3gp: {}
        video/avi: {}
        video/mp4: {}
        video/mpeg: {}
        video/quicktime: {}
        video/webm: {}
        video/x-msvideo: {}
    400:
      description: 入力バリデーションエラー
      content:
        application/json:
          schema:
            properties:
              error_message:
                example: 入力値が不正です
    404:
      description: 指定のルーティング外
      content:
        application/json:
          schema:
            properties:
              error_message:
                example: アクセス方法を再度確認してください
    405:
      description: 指定のメソッド外
      content:
        application/json:
          schema:
            properties:
              error_message:
                example: アクセス方法を再度確認してください
    500:
      description: サーバーエラー
      content:
        application/json:
          schema:
            properties:
              error_message:
                example: サーバーでエラーが発生しました
